
image: cypress/base:16

stages:
  - test

variables:
  npm_config_cache: '$CI_PROJECT_DIR/.npm'
  CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/*
    - cache/Cypress
    - node_modules
    - build

test_on_main:
  stage: test
  script:
    - npm ci
    - npx cypress run --record
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == "main"'
  tags:
    - docker1

test_on_other_branches:
  stage: test
  script:
    - npm ci
    - npx cypress run
  rules:
    - if: '$CI_COMMIT_BRANCH != "main"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  tags:
    - docker1

downstream_test:
  stage: test
  script:
    - npm ci
    - npx cypress run
  rules:
    - if: '$CI_PIPELINE_SOURCE == "pipeline"'
  tags:
    - docker1

